name: Build

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: devkitpro/devkita64:latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - name: Install latest libnx (before building)
        run: |
          pushd /tmp
          git clone https://github.com/switchbrew/libnx
          cd libnx
          make clean
          make -j8 PREFIX="ccache aarch64-none-elf-"
          make install
          popd

      - name: Build
        run: make -j8 PREFIX="ccache aarch64-none-elf-"

      - name: Upload built files
        uses: actions/upload-artifact@v6
        with:
          name: sdcard
          path: out/sd
